name = "my-app-web" # TODO: Change this to your app name
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
send_metrics = false
main = "worker.ts"

# Serve static assets
[site]
bucket = "./build/client"

# For production deployment with custom domain
# route = "app.your-domain.com/*"
# workers_dev = false

# For development/preview
workers_dev = true

# Environment variables
[vars]
NODE_ENV = "production"

# KV namespace for caching and sessions
# TODO: Create namespace with: wrangler kv:namespace create "CACHE"
# Then update the ID below
[[kv_namespaces]]
binding = "CAI_CACHE"
id = "YOUR_KV_NAMESPACE_ID" # TODO: Replace with your KV namespace ID

# D1 Database (uncomment and configure when needed)
# TODO: Create database with: wrangler d1 create my-app-db
# [[d1_databases]]
# binding = "DB"
# database_name = "my-app-db"
# database_id = "YOUR_D1_DATABASE_ID"

# R2 Storage (uncomment and configure when needed)
# TODO: Create bucket with: wrangler r2 bucket create my-app-storage
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "my-app-storage"

# Durable Objects (uncomment and configure when needed)
# [[durable_objects.bindings]]
# name = "COUNTER"
# class_name = "Counter"
# script_name = "worker"

[env.preview]
name = "my-app-web-preview" # TODO: Change this to your app name
workers_dev = true
vars = { NODE_ENV = "development" }