// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/password-reset/update-password": {
    params: {};
  };
  "/password-reset": {
    params: {};
  };
  "/virtualized-list": {
    params: {};
  };
  "/catalyst-test": {
    params: {};
  };
  "/data-fetching": {
    params: {};
  };
  "/params/:id": {
    params: {
      "id": string;
    };
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/ssr": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/password-reset/update-password" | "/password-reset" | "/virtualized-list" | "/catalyst-test" | "/data-fetching" | "/params/:id" | "/sign-in" | "/sign-up" | "/ssr";
  };
  "routes/password-reset.update-password.tsx": {
    id: "routes/password-reset.update-password";
    page: "/password-reset/update-password";
  };
  "routes/password-reset._index.tsx": {
    id: "routes/password-reset._index";
    page: "/password-reset";
  };
  "routes/virtualized-list.tsx": {
    id: "routes/virtualized-list";
    page: "/virtualized-list";
  };
  "routes/catalyst-test.tsx": {
    id: "routes/catalyst-test";
    page: "/catalyst-test";
  };
  "routes/data-fetching.tsx": {
    id: "routes/data-fetching";
    page: "/data-fetching";
  };
  "routes/params.$id.tsx": {
    id: "routes/params.$id";
    page: "/params/:id";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/ssr.tsx": {
    id: "routes/ssr";
    page: "/ssr";
  };
};