name = "cai-web"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
send_metrics = false
main = ".open-next/worker.js"

# For production deployment with custom domain
# route = "app.your-domain.com/*"
# workers_dev = false

# For development/preview
workers_dev = true

# KV namespace for caching
[[kv_namespaces]]
binding = "CAI_CACHE"
id = "YOUR_KV_NAMESPACE_ID"

[env.preview]
name = "cai-web-preview"
workers_dev = true
